sonar.organization=phoenix-event-ticketing
sonar.projectKey=Phoenix-Event-Ticketing_phoenix-online-event-service
sonar.projectName=phoenix-online-event-service
sonar.sources=src

sonar.exclusions=**/node_modules/**,**/*.min.js

sonar.tests=tests
sonar.test.inclusions=**/*.test.js
sonar.qualitygate.wait=false
